[icedos.desktop.cosmic.panel]
autohide = false
expand = true
gaps = false
monitor = "" # Example "DP-2"
position = "Top" # Left, Right, Top, Bottom
themeMode = "ThemeDefault" # ThemeDefault, Dark, Light
size = "XS" # XS, S, M, L, XL
opacity = 100 # Percentage

[icedos.desktop.cosmic.panel.plugins]
left = ["com.system76.CosmicAppletWorkspaces"]
center = ["com.system76.CosmicAppList"]
right = [
  "dev.dominiccgeh.CosmicAppletEmojiSelector",
  "io.github.cosmic_utils.cosmic-ext-applet-clipboard-manager",
  "com.system76.CosmicAppletStatusArea",
  "com.system76.CosmicAppletInputSources",
  "net.tropicbliss.CosmicExtAppletCaffeine",
  "com.system76.CosmicAppletBluetooth",
  "com.system76.CosmicAppletAudio",
  "com.system76.CosmicAppletBattery",
  "com.system76.CosmicAppletNetwork",
  "com.system76.CosmicAppletNotifications",
  "com.system76.CosmicAppletTime",
  "com.system76.CosmicAppletPower",
]

[icedos.desktop.cosmic.users.username]
panelFavorites = []
