[icedos.desktop.cosmic.input.keyboard]
alternateCharactersKey = "" # lalt, ralt, lwin, rwin, menu, caps
capsLockKey = "" # escape, swapescape, backspace, super, ctrl_modifier
composeKey = "" # ralt, lwin, rwin, menu, rctrl, caps, sclk, prsc
keyboardLayouts = "us,gr"
numlock = "BootOn" # BootOff, BootOn, LastBoot
repeatDelay = 600
repeatRate = 25
shortcuts = ""
superKeyAction = "WorkspaceOverview" # Launcher, WorkspaceOverview, AppLibrary, Disable

[icedos.desktop.cosmic.input.mouse]
acceleration = false
mouseSpeed = 50 # 0 - 100
naturalScrolling = false
primaryButtonRight = false
scrollingSpeed = 50 # 1 - 100
