[icedos.desktop.cosmic.windowManagement.controls]
activeHint = false
maximize = true
minimize = true

[icedos.desktop.cosmic.windowManagement.focus]
cursorFollowsFocus = false
followsCursor = false
followsCursorDelay = 0 # ms

[icedos.desktop.cosmic.windowManagement.snapWindowsToEdges]
enable = true
threshold = 25
